// <auto-generated />
using System;
using InventoryManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace InventoryManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319221622_AddCustomIdToInventory")]
    partial class AddCustomIdToInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryManager.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("CustomBool1Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomBool1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomBool1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomBool2Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomBool2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomBool2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomBool3Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomBool3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomBool3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomBool3State")
                        .HasColumnType("boolean");

                    b.Property<int>("CustomIdCounter")
                        .HasColumnType("integer");

                    b.Property<string>("CustomIdTemplate")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomInt1Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomInt1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomInt1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomInt2Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomInt2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomInt2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomInt3Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomInt3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomInt3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomInt3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink1Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomLink1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomLink1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink2Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomLink2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomLink2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomLink3Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomLink3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomLink3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomLink3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString1Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomString1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomString1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString2Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomString2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomString2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomString3Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomString3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomString3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomString3State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText1Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomText1Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText1ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomText1State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText2Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomText2Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText2ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomText2State")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomText3Description")
                        .HasColumnType("text");

                    b.Property<string>("CustomText3Name")
                        .HasColumnType("text");

                    b.Property<bool>("CustomText3ShowInTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomText3State")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "Description" });

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InventoryId", "UserId")
                        .IsUnique();

                    b.ToTable("InventoryAccesses");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryComments");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryTag", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("InventoryTags");
                });

            modelBuilder.Entity("InventoryManager.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<bool>("CustomBool1")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomBool2")
                        .HasColumnType("boolean");

                    b.Property<bool>("CustomBool3")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("CustomInt1")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomInt2")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomInt3")
                        .HasColumnType("integer");

                    b.Property<string>("CustomLink1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomLink2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomLink3")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomString1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomString2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomString3")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomText1")
                        .HasColumnType("text");

                    b.Property<string>("CustomText2")
                        .HasColumnType("text");

                    b.Property<string>("CustomText3")
                        .HasColumnType("text");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "CustomString1", "CustomString2", "CustomString3", "CustomId" });

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InventoryId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventoryManager.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ItemId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("InventoryManager.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("InventoryManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryManager.Models.Inventory", b =>
                {
                    b.HasOne("InventoryManager.Models.User", "CreatedBy")
                        .WithMany("OwnedInventories")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryAccess", b =>
                {
                    b.HasOne("InventoryManager.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryComment", b =>
                {
                    b.HasOne("InventoryManager.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManager.Models.InventoryTag", b =>
                {
                    b.HasOne("InventoryManager.Models.Inventory", "Inventory")
                        .WithMany("InventoryTags")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManager.Models.Tag", "Tag")
                        .WithMany("InventoryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InventoryManager.Models.Item", b =>
                {
                    b.HasOne("InventoryManager.Models.User", "CreatedBy")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManager.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("InventoryManager.Models.Like", b =>
                {
                    b.HasOne("InventoryManager.Models.Item", "Item")
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManager.Models.Inventory", b =>
                {
                    b.Navigation("InventoryTags");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryManager.Models.Item", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("InventoryManager.Models.Tag", b =>
                {
                    b.Navigation("InventoryTags");
                });

            modelBuilder.Entity("InventoryManager.Models.User", b =>
                {
                    b.Navigation("CreatedItems");

                    b.Navigation("OwnedInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
